Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto_Notas.Models;

namespace Proyecto_Notas.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly MerMariaJuliaContext _context;

        public EstudiantesController(MerMariaJuliaContext context)
        {
            _context = context;
        }

        // GET: Estudiantes
        public async Task<IActionResult> Index()
        {
              return _context.Estudiantes != null ? 
                          View(await _context.Estudiantes.ToListAsync()) :
                          Problem("Entity set 'MerMariaJuliaContext.Estudiantes'  is null.");
        }

        // GET: Estudiantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.IdEstudiante == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Estudiantes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdEstudiante,Nombre,Apellido,Correo,Celular,Edad")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdEstudiante,Nombre,Apellido,Correo,Celular,Edad")] Estudiante estudiante)
        {
            if (id != estudiante.IdEstudiante)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.IdEstudiante))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Estudiantes == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.IdEstudiante == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Estudiantes == null)
            {
                return Problem("Entity set 'MerMariaJuliaContext.Estudiantes'  is null.");
            }
            var estudiante = await _context.Estudiantes.FindAsync(id);
            if (estudiante != null)
            {
                _context.Estudiantes.Remove(estudiante);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
          return (_context.Estudiantes?.Any(e => e.IdEstudiante == id)).GetValueOrDefault();
        }
    }
}

Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Proyecto_Notas.Models;
using static System.Net.Mime.MediaTypeNames;

namespace Proyecto_Notas.Controllers
{
    public class NotasController : Controller
    {
        private readonly MerMariaJuliaContext _context;

        public NotasController(MerMariaJuliaContext context)
        {
            _context = context;
        }

        // GET: Notas
        public async Task<IActionResult> Index()
        {
            var merMariaJuliaContext = _context.Notas.Include(n => n.IdEstudianteNavigation).Include(n => n.IdMateriaNavigation).ToList();
            return View(merMariaJuliaContext);
        }

        // GET: Notas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .Include(n => n.IdEstudianteNavigation)
                .Include(n => n.IdMateriaNavigation)
                .FirstOrDefaultAsync(m => m.IdNota == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // GET: Notas/Create
        public IActionResult Create()
        {

                ViewData["IdEstudiante"] = new SelectList(_context.Estudiantes.Select(e => new {
                    e.IdEstudiante,
                    FullName = $"{e.Nombre} {e.Apellido}"
                }), "IdEstudiante", "FullName");
                ViewData["IdMateria"] = new SelectList(_context.Materias, "IdMateria", "NombreMateria");
                return View();
        }

        // POST: Notas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdNota,IdEstudiante,IdMateria,Nota1")] Nota nota)
        {
            // Verificar si ya existe una nota para este estudiante y esta materia
            var existeNota = await _context.Notas.FirstOrDefaultAsync(n => n.IdEstudiante == nota.IdEstudiante && n.IdMateria == nota.IdMateria);

            if (existeNota != null)
            {
                ModelState.AddModelError(string.Empty, "Este estudiante ya tiene una nota para esta materia.");
                ViewData["IdEstudiante"] = new SelectList(_context.Estudiantes.Select(e => new {
                    e.IdEstudiante,
                    FullName = $"{e.Nombre} {e.Apellido}"
                }), "IdEstudiante", "FullName");
                ViewBag.IdMateria = new SelectList(_context.Materias, "IdMateria", "NombreMateria", nota.IdMateria);
                return View(nota);
            }
            // Fin de Verificacion
            if (ModelState.IsValid)
            {
                _context.Add(nota);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstudiante"] = new SelectList(_context.Estudiantes.Select(e => new {
                e.IdEstudiante,
                FullName = $"{e.Nombre} {e.Apellido}"
            }), "IdEstudiante", "FullName");
            ViewBag.IdMateria = new SelectList(_context.Materias, "IdMateria", "NombreMateria");

            return View(nota);
        }

        // GET: Notas/Edit/5
        public async Task<IActionResult> EditAsync(int id)
        {

            var nota = _context.Notas.SingleOrDefault(n => n.IdNota == id);

            if (nota == null)
            {
                return NotFound();
            }

            var estudiantes = _context.Estudiantes.ToList();
            var materias = _context.Materias.ToList();

            ViewBag.IdEstudiante = new SelectList(_context.Estudiantes.Select(e => new
            {
                e.IdEstudiante,
                FullName = e.Nombre + " " + e.Apellido
            }), "IdEstudiante", "FullName", nota.IdEstudiante);
            ViewData["Materias"] = new SelectList(materias, "IdMateria", "NombreMateria", nota.IdMateria);

            return View(nota);
        }

        // POST: Notas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdNota,IdEstudiante,IdMateria,Nota1")] Nota nota)
        {
            if (id != nota.IdNota)
            {
                return NotFound();
            }

            // Obtener la nota actual de la base de datos
            var notaActual = _context.Notas.AsNoTracking().SingleOrDefault(n => n.IdNota == id);

            // Verificar si el estudiante ya tiene una nota registrada para la materia
            var notaExistente = _context.Notas.AsNoTracking().SingleOrDefault(n => n.IdEstudiante == nota.IdEstudiante && n.IdMateria == nota.IdMateria);

            // Si se encuentra una nota y los IDs son diferentes, mostrar un mensaje de error
            if (notaExistente != null && notaExistente.IdNota != id)
            {
                ModelState.AddModelError("", "El estudiante ya tiene una nota registrada para esta materia.");

                ViewBag.IdEstudiante = new SelectList(_context.Estudiantes.Select(e => new
                {
                    e.IdEstudiante,
                    FullName = e.Nombre + " " + e.Apellido
                }), "IdEstudiante", "FullName", nota.IdEstudiante);
                ViewBag.IdMateria = new SelectList(_context.Materias, "IdMateria", "NombreMateria", nota.IdMateria);
                return View(nota);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotaExists(nota.IdNota))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
            var estudiantes = _context.Estudiantes.ToList();
            var materias = _context.Materias.ToList();

            ViewBag.IdEstudiante = new SelectList(_context.Estudiantes.Select(e => new
            {
                e.IdEstudiante,
                FullName = e.Nombre + " " + e.Apellido
            }), "IdEstudiante", "FullName", nota.IdEstudiante);
            ViewData["Materias"] = new SelectList(materias, "IdMateria", "NombreMateria", nota.IdMateria);

            return View(nota);
        }

        // GET: Notas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .Include(n => n.IdEstudianteNavigation)
                .Include(n => n.IdMateriaNavigation)
                .FirstOrDefaultAsync(m => m.IdNota == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // POST: Notas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notas == null)
            {
                return Problem("Entity set 'MerMariaJuliaContext.Notas'  is null.");
            }
            var nota = await _context.Notas.FindAsync(id);
            if (nota != null)
            {
                _context.Notas.Remove(nota);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotaExists(int id)
        {
            return (_context.Notas?.Any(e => e.IdNota == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Instituto Maria Julia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proyecto_Notas.styles.css" asp-append-version="true" />

        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.111.3">
    <title>Features · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/features/">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proyecto_Notas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
@*                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="privacy">privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Estudiantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materias" asp-action="Index">Materias</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notas" asp-action="Index">Registro Notas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Instituto Maria Julia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>